#开发环境配置
server:
  port: 9090
  tomcat:
    accept-count: 1000        #tomcat任务队列容量
    max-connections: 2000    #最大连接数
    connection-timeout: 5000 #最长等待时间，如果没有数据进来，等待一段时间后断开连接，释放线程
    threads:
      max: 200
      min-spare: 100